[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
